# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_auto_20180625_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='line_billed_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Line Billed Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='line_received_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Line Received Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='line_shipped_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Line Shipped Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='order_lines_quantity_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Order Lines Quantity Summation'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Product Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='quantity_promised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Promised Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Received Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='quantity_shipped',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Shipped Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='scheduled_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Schedule Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='supplier_suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Supplier Suggested Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_billed_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Line Billed Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_received_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Line Received Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_shipped_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Line Shipped Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='order_lines_quantity_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Order Lines Quantity Summation'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Product Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity_promised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Promised Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Received Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity_shipped',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Shipped Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='scheduled_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Schedule Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='supplier_suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Supplier Suggested Price'),
        ),
    ]
