# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_auto_20180626_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='network_id',
        ),
    ]
