# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_orders', '0005_purchaseorderline_network_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderheader',
            name='buyer_email',
        ),
        migrations.AddField(
            model_name='purchaseorderheader',
            name='owner',
            field=models.ForeignKey(help_text=set(['Buyer Is The Owner of Purchase Order']), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
