# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0002_salesorderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderheader',
            name='purchase_order_header_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='purchase_order_header_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='purchase_order_line_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
